CC ?= cc
AR ?= ar

../comobj.a:	auxf.o chkid.o chksid.o cmpdate.o date_ab.o date_ba.o del_ab.o del_ba.o dodelt.o dofile.o dohist.o doie.o dolist.o encode.o eqsid.o flushto.o fmterr.o getline.o getser.o logname.o newsid.o newstats.o permiss.o pf_ab.o putline.o rdmod.o setup.o sid_ab.o sid_ba.o sidtoser.o sinit.o stats_ab.o strptim.o
	$(AR) rv ../comobj.a auxf.o chkid.o chksid.o cmpdate.o date_ab.o date_ba.o del_ab.o del_ba.o dodelt.o dofile.o dohist.o doie.o dolist.o encode.o eqsid.o flushto.o fmterr.o getline.o getser.o logname.o newsid.o newstats.o permiss.o pf_ab.o putline.o rdmod.o setup.o sid_ab.o sid_ba.o sidtoser.o sinit.o stats_ab.o strptim.o

auxf.o:	auxf.c
	$(CC) $(CFLAGS) -I../../hdr -c -o auxf.o auxf.c

chkid.o:	chkid.c
	$(CC) $(CFLAGS) -I../../hdr -c -o chkid.o chkid.c

chksid.o:	chksid.c
	$(CC) $(CFLAGS) -I../../hdr -c -o chksid.o chksid.c

cmpdate.o:	cmpdate.c
	$(CC) $(CFLAGS) -I../../hdr -c -o cmpdate.o cmpdate.c

date_ab.o:	date_ab.c
	$(CC) $(CFLAGS) -I../../hdr -c -o date_ab.o date_ab.c

date_ba.o:	date_ba.c
	$(CC) $(CFLAGS) -I../../hdr -c -o date_ba.o date_ba.c

del_ab.o:	del_ab.c
	$(CC) $(CFLAGS) -I../../hdr -c -o del_ab.o del_ab.c

del_ba.o:	del_ba.c
	$(CC) $(CFLAGS) -I../../hdr -c -o del_ba.o del_ba.c

dodelt.o:	dodelt.c
	$(CC) $(CFLAGS) -I../../hdr -c -o dodelt.o dodelt.c

dofile.o:	dofile.c
	$(CC) $(CFLAGS) -I../../hdr -c -o dofile.o dofile.c

dohist.o:	dohist.c
	$(CC) $(CFLAGS) -I../../hdr -c -o dohist.o dohist.c

doie.o:	doie.c
	$(CC) $(CFLAGS) -I../../hdr -c -o doie.o doie.c

dolist.o:	dolist.c
	$(CC) $(CFLAGS) -I../../hdr -c -o dolist.o dolist.c

encode.o:	encode.c
	$(CC) $(CFLAGS) -I../../hdr -c -o encode.o encode.c

eqsid.o:	eqsid.c
	$(CC) $(CFLAGS) -I../../hdr -c -o eqsid.o eqsid.c

flushto.o:	flushto.c
	$(CC) $(CFLAGS) -I../../hdr -c -o flushto.o flushto.c

fmterr.o:	fmterr.c
	$(CC) $(CFLAGS) -I../../hdr -c -o fmterr.o fmterr.c

getline.o:	getline.c
	$(CC) $(CFLAGS) -I../../hdr -c -o getline.o getline.c

getser.o:	getser.c
	$(CC) $(CFLAGS) -I../../hdr -c -o getser.o getser.c

logname.o:	logname.c
	$(CC) $(CFLAGS) -I../../hdr -c -o logname.o logname.c

newsid.o:	newsid.c
	$(CC) $(CFLAGS) -I../../hdr -c -o newsid.o newsid.c

newstats.o:	newstats.c
	$(CC) $(CFLAGS) -I../../hdr -c -o newstats.o newstats.c

permiss.o:	permiss.c
	$(CC) $(CFLAGS) -I../../hdr -c -o permiss.o permiss.c

pf_ab.o:	pf_ab.c
	$(CC) $(CFLAGS) -I../../hdr -c -o pf_ab.o pf_ab.c

putline.o:	putline.c
	$(CC) $(CFLAGS) -I../../hdr -c -o putline.o putline.c

rdmod.o:	rdmod.c
	$(CC) $(CFLAGS) -I../../hdr -c -o rdmod.o rdmod.c

setup.o:	setup.c
	$(CC) $(CFLAGS) -I../../hdr -c -o setup.o setup.c

sid_ab.o:	sid_ab.c
	$(CC) $(CFLAGS) -I../../hdr -c -o sid_ab.o sid_ab.c

sid_ba.o:	sid_ba.c
	$(CC) $(CFLAGS) -I../../hdr -c -o sid_ba.o sid_ba.c

sidtoser.o:	sidtoser.c
	$(CC) $(CFLAGS) -I../../hdr -c -o sidtoser.o sidtoser.c

sinit.o:	sinit.c
	$(CC) $(CFLAGS) -I../../hdr -c -o sinit.o sinit.c

stats_ab.o:	stats_ab.c
	$(CC) $(CFLAGS) -I../../hdr -c -o stats_ab.o stats_ab.c

strptim.o:	strptim.c
	$(CC) $(CFLAGS) -I../../hdr -c -o strptim.o strptim.c

clean:
	rm -f ../comobj.a auxf.o chkid.o chksid.o cmpdate.o date_ab.o date_ba.o del_ab.o del_ba.o dodelt.o dofile.o dohist.o doie.o dolist.o encode.o eqsid.o flushto.o fmterr.o getline.o getser.o logname.o newsid.o newstats.o permiss.o pf_ab.o putline.o rdmod.o setup.o sid_ab.o sid_ba.o sidtoser.o sinit.o stats_ab.o strptim.o
