../libt4013.a:	arc.o box.o circle.o close.o dot.o erase.o label.o line.o linemod.o move.o open.o point.o scale.o space.o subr.o
	$(AR) rc ../libt4013.a arc.o box.o circle.o close.o dot.o erase.o label.o line.o linemod.o move.o open.o point.o scale.o space.o subr.o

arc.o:	arc.c
	$(CC) $(CFLAGS) -c -o arc.o arc.c

box.o:	box.c
	$(CC) $(CFLAGS) -c -o box.o box.c

circle.o:	circle.c
	$(CC) $(CFLAGS) -c -o circle.o circle.c

close.o:	close.c
	$(CC) $(CFLAGS) -c -o close.o close.c

dot.o:	dot.c
	$(CC) $(CFLAGS) -c -o dot.o dot.c

erase.o:	erase.c
	$(CC) $(CFLAGS) -c -o erase.o erase.c

label.o:	label.c
	$(CC) $(CFLAGS) -c -o label.o label.c

line.o:	line.c
	$(CC) $(CFLAGS) -c -o line.o line.c

linemod.o:	linemod.c
	$(CC) $(CFLAGS) -c -o linemod.o linemod.c

move.o:	move.c
	$(CC) $(CFLAGS) -c -o move.o move.c

open.o:	open.c
	$(CC) $(CFLAGS) -c -o open.o open.c

point.o:	point.c
	$(CC) $(CFLAGS) -c -o point.o point.c

scale.o:	scale.c
	$(CC) $(CFLAGS) -c -o scale.o scale.c

space.o:	space.c
	$(CC) $(CFLAGS) -c -o space.o space.c

subr.o:	subr.c
	$(CC) $(CFLAGS) -c -o subr.o subr.c

clean:
	rm -f ../libt4013.a arc.o box.o circle.o close.o dot.o erase.o label.o line.o linemod.o move.o open.o point.o scale.o space.o subr.o
