all:
	make -C dumb
	make -C imagen
	make -C t4013
	make -C vt0
	make -C gigi
	make -C plot
	make -C t4014
	make -C aed
	make -C hp2648
	make -C t300
	make -C t450
	make -C bitgraph
	make -C hp7221
	make -C t300s
	make -C tf77

clean:
	make -C dumb clean
	make -C imagen clean
	make -C t4013 clean
	make -C vt0 clean
	make -C gigi clean
	make -C plot clean
	make -C t4014 clean
	make -C aed clean
	make -C hp2648 clean
	make -C t300 clean
	make -C t450 clean
	make -C bitgraph clean
	make -C hp7221 clean
	make -C t300s clean
	make -C tf77 clean

install:
	make -C dumb install
	make -C imagen install
	make -C t4013 install
	make -C vt0 install
	make -C gigi install
	make -C plot install
	make -C t4014 install
	make -C aed install
	make -C hp2648 install
	make -C t300 install
	make -C t450 install
	make -C bitgraph install
	make -C hp7221 install
	make -C t300s install
	make -C tf77 install
