../libplot.a:	arc.o box.o circle.o close.o cont.o dot.o erase.o label.o line.o linmod.o move.o open.o point.o putsi.o space.o
	$(AR) rc ../libplot.a arc.o box.o circle.o close.o cont.o dot.o erase.o label.o line.o linmod.o move.o open.o point.o putsi.o space.o

arc.o:	arc.c
	$(CC) $(CFLAGS) -c -o arc.o arc.c

box.o:	box.c
	$(CC) $(CFLAGS) -c -o box.o box.c

circle.o:	circle.c
	$(CC) $(CFLAGS) -c -o circle.o circle.c

close.o:	close.c
	$(CC) $(CFLAGS) -c -o close.o close.c

cont.o:	cont.c
	$(CC) $(CFLAGS) -c -o cont.o cont.c

dot.o:	dot.c
	$(CC) $(CFLAGS) -c -o dot.o dot.c

erase.o:	erase.c
	$(CC) $(CFLAGS) -c -o erase.o erase.c

label.o:	label.c
	$(CC) $(CFLAGS) -c -o label.o label.c

line.o:	line.c
	$(CC) $(CFLAGS) -c -o line.o line.c

linmod.o:	linmod.c
	$(CC) $(CFLAGS) -c -o linmod.o linmod.c

move.o:	move.c
	$(CC) $(CFLAGS) -c -o move.o move.c

open.o:	open.c
	$(CC) $(CFLAGS) -c -o open.o open.c

point.o:	point.c
	$(CC) $(CFLAGS) -c -o point.o point.c

putsi.o:	putsi.c
	$(CC) $(CFLAGS) -c -o putsi.o putsi.c

space.o:	space.c
	$(CC) $(CFLAGS) -c -o space.o space.c

clean:
	rm -f ../libplot.a arc.o box.o circle.o close.o cont.o dot.o erase.o label.o line.o linmod.o move.o open.o point.o putsi.o space.o
